### PR TITLE
Merge master into feature/CommandLanguage

### PR DESCRIPTION
**Pull request by mpowelson**
Merges master into feature/CommandLanguage to resolve conflicts.

### CODE REVIEW

**Comment by mpowelson** [comment]
#229 Should not have any conflicts once this is merged.

**Comment by Levi-Armstrong** [comment]
I believe this is reverting changes from the most recent PR into feature/CommandLanguage?

**Comment by mpowelson** [comment]
> I believe this is reverting changes from the most recent PR into feature/CommandLanguage?

If something was merged since I made it, maybe. This should just merge master into command language.  There were a couple of files that conflicted. You can probably push the changes directly to command language if you want. I just didn't have permissions to do that.

**Comment by Levi-Armstrong** [comment]
Addressed by #231

**Pull request closed without merging**
