### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by mohamedsayed18**
Signed-off-by: mohamedsayed18 <mohamed95.a.s@gmail.com>

### CODE REVIEW

**Comment by mpowelson** [comment]
Looks fine to me. I will note that there is a typo in your commit message if you want to fix that.

**Comment by mohamedsayed18** [comment]
I will fix it

**Comment by mohamedsayed18** [comment]
There is another thing that need to be changed I will do them and open the pull request again

**Comment by mohamedsayed18** [comment]
[Raster_path_plan](https://github.com/ros-industrial-consortium/trajopt_ros#raster-path-plan). Launch file doesn't exist
Should we remove this section from the readme?

**Comment by Levi-Armstrong** [comment]
> [Raster_path_plan](https://github.com/ros-industrial-consortium/trajopt_ros#raster-path-plan). Launch file doesn't exist
> Should we remove this section from the readme?

Ah, so we moved all of the examples to tesseract_ros_examples. It may be good to keep them but update the readme to direct the reader to tesseract_ros_examples repository. What do you think?

**Comment by mohamedsayed18** [comment]
> Ah, so we moved all of the examples to tesseract_ros_examples. It may be good to keep them but update the readme to direct the reader to tesseract_ros_examples repository. What do you think?

I agree with you but I can't find the Raster_path launch file in tesseract_ros_examples

**Comment by Levi-Armstrong** [comment]
Your right. It looks like that one never got migrated. I am good with removing it.

**Comment by mohamedsayed18** [comment]
> Your right. It looks like that one never got migrated. I am good with removing it.

Removed

**Comment by Levi-Armstrong** [comment]
@mohamedsayed18 Thanks you!

**Pull request merged**
