### PR TITLE
Shrink trust region if convex solver fails

### PR DESCRIPTION
**Pull request by mpowelson**
I'm not sure if this is a good idea or not. I'm testing it out, and it seems promising. However, I'm putting this here so others can test it out.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
This looks reasonable. I have been seeing more QP solver failures since we switched to OSQP so I will test. Also if this works I think the default trust region may be to large.

**Comment by mpowelson** [comment]
For my problem it seems like this works about half the time. About half the time of it fails once it will fail a bunch of times in a row. They other half it will fail once or twice but then succeed with the smaller trust region. 

I'm curious what other things solvers like snopt do to mitigate this. Maybe we could relax constraints, solve, and then reapply them? I'd really rather not put too much more effort into this solver though. If we do anything major is rather do it in trajopt_sqp.

**Comment by Levi-Armstrong** [comment]
It may be worth trying where we start out with everything as a cost for a few iteration and then witch them to constraints. I believe this what you are referring to by relax the constraints? 

> I'd really rather not put too much more effort into this solver though. If we do anything major is rather do it in trajopt_sqp.
I agree, do we have a list of what is left to do before making the jump?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn You recent asked this question in the annual meeting. Do you have thoughts on the subject?

**Comment by mpowelson** [comment]
For me, the limitation is time to update my code. I think trajopt_ifopt is probably useable as is. We do have #183 where we are keeping a list. I think #193 is probably the main thing you would miss.

**Comment by mpowelson** [comment]
I've also pondered seeing if we should put trajopt_sqp in its own repo and push back an interface to it to ifopt like they have for ipopt and snopt. The free SQP optimizer might be useful to people outside of trajopt, and we might get input from actual optimization experts.

**Comment by mpowelson** [comment]
Removing the wip since I am using this, and it seems to work fine. I can keep using it for a week or so and see if anything pops up if you want, or we can merge it.

**Review by Levi-Armstrong — APPROVED** [review]
If you have been using it without issues then I am good with you merging it.

**Pull request merged**
