### PR TITLE
Example unit test

### PR DESCRIPTION
**Pull request by mpowelson**
Adds unit tests to run all of the examples. Depends on #73 . 

Still WIP because car_seat_demo is broken (see [tesseract issue 71](https://github.com/ros-industrial-consortium/tesseract/issues/71#)).

### CODE REVIEW

**Comment by mpowelson** [comment]
@Levi-Armstrong Also note that glass upright and basic cartesian are are hardcoded to use the json method. How should I address that?

**Comment by Levi-Armstrong** [comment]
What is the current issue with just using json method?

**Comment by mpowelson** [comment]
If we break something in the C++ interface at runtime this won't catch it. I could add it as a ROS param, but I was not sure how to best include that in the test. I suppose I could just launch the node twice, one with each param value.

**Comment by Levi-Armstrong** [comment]
You should be able to pass arguments to the launch file as shown below. You could add two test in the CMakeLists.txt passing an argument telling it to use json file or c++.
```
add_rostest(test/testlaunchfile.test ARGS argument1:=vaule1 argument2:=value2)
```

**Comment by mpowelson** [comment]
I didn't do that because I am using add_rostest_gtest which seems to make an executable? I didn't want to have 2 executables for each. Maybe I have this structured inefficiently. I just launched 2 different test nodes in the launch file.

**Comment by mpowelson** [comment]
@Levi-Armstrong I forgot that we need to add the motoman driver to CI or else the car seat demo is going to fail. How should I go about that?

**Comment by mpowelson** [comment]
@Levi-Armstrong Do you want to merge this into kinetic-devel or should I close this and open one against Tesseract? Or is this already done in Tesseract?

Regardless, I think the cmake method of running these might be cleaner anyway.

**Comment by Levi-Armstrong** [comment]
Open against tesseract?

**Comment by mpowelson** [comment]
Didn't all of the examples get moved to tesseract?

**Pull request closed without merging**
