### PR TITLE
Fix misnaming of constraints

### LINKED ISSUE #236: Trajopt constraints getting misnamed
I'm not sure if it is limited to naming or if something worse is happening here. However I print out the details of each term inside hatch, then when the optimization is running one of them always seems to get lost. Here is an example where waypoint_40 seems to get messed up

```
Joint Pos, name: joint_waypoint_0 coeffs:5 5 5 5 5  targets:        0.17        3.04        0.05        0.07 7.77563e-17  first: 0  last: 0
upper: 0 0 0 0 0  lower: 0 0 0 0 0
Joint Pos, name: joint_waypoint_10 coeffs:5 5 5 5 5  targets:        0.17        3.04         0.1        0.07 7.77563e-17  first: 10  last: 10
upper:      0.2 0.523599      0.2 0.523599        0  lower:      -0.2 -0.523599      -0.2 -0.523599         0
Joint Pos, name: joint_waypoint_20 coeffs:5 5 5 5 5  targets: 0.830141  2.99159 0.121999        0        0  first: 20  last: 20
upper:      0.2 0.523599      0.2 0.523599        0  lower:      -0.2 -0.523599      -0.2 -0.523599         0
Joint Pos, name: joint_waypoint_30 coeffs:5 5 5 5 5  targets: 0.830141  2.99159 0.121999  1.19233        0  first: 30  last: 30
upper:      0.2 0.523599      0.2 0.523599        0  lower:      -0.2 -0.523599      -0.2 -0.523599         0
Joint Pos, name: joint_waypoint_40 coeffs:5 5 5 5 5  targets: 0.830141  2.99159 0.402696  1.19233        0  first: 40  last: 40
upper:      0.2 0.523599      0.2 0.523599        0  lower:      -0.2 -0.523599      -0.2 -0.523599         0
Joint Pos, name: joint_waypoint_50 coeffs:5 5 5 5 5  targets: 0.830141  2.47286 0.402696  1.19233        0  first: 50  last: 50
upper: 0 0 0 0 0  lower: 0 0 0 0 0
[INFO] iteration 1
[INFO]  
                |      merit |   oldexact |  new_exact |    dapprox |     dexact |      ratio
          COSTS | ---------------------------------------------------------------------------
 joint_vel_cost | ---------- |  2.216e+02 |  2.216e+02 |  3.780e-12 | -2.842e-13 |   ------  
    CONSTRAINTS | ----------------------------------------------------------------- ---------
joint_waypoint_0 |  1.000e+01 |  0.000e+00 |  9.861e-30 | -1.776e-14 | -9.861e-30 |   ------  
     JointPosEq |  1.000e+01 |  0.000e+00 | 1.821e-138 | -9.542e-69 | -1.821e-138 |   ------  
joint_waypoint_10 |  1.000e+01 |  0.000e+00 |  0.000e+00 | -4.930e-31 |  0.000e+00 |   ------  
joint_waypoint_20 |  1.000e+01 |  0.000e+00 |  0.000e+00 | -9.269e-24 |  0.000e+00 |   ------  
joint_waypoint_30 |  1.000e+01 |  0.000e+00 |  0.000e+00 | -1.186e-31 |  0.000e+00 |   ------  
joint_waypoint_50 |  1.000e+01 |  0.000e+00 |  0.000e+00 | -1.384e-38 |  0.000e+00 |   ------  

```

### PR DESCRIPTION
**Pull request by mpowelson**
Closes #236

### CODE REVIEW

**Comment by mpowelson** [comment]
This looks like it is failing for the same reason master is.

**Comment by Levi-Armstrong** [comment]
Do you know why they are failing?

**Comment by mpowelson** [comment]
> Do you know why they are failing?

Not offhand. I'd have to look into it.

**Comment by Levi-Armstrong** [comment]
Well not sure what the issues is, I ran the tests locally and they pass for me. Do they pass for you locally?

**Comment by mpowelson** [comment]
> Well not sure what the issues is, I ran the tests locally and they pass for me. Do they pass for you locally?

I haven't actually tried. Nothing has changed in trajopt_sqp recently, so it is odd that it is failing. I can try to look into this tomorrow.

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
