### PR TITLE
Add trajopt_ifopt.h

### PR DESCRIPTION
**Pull request by mpowelson**

### CODE REVIEW

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by mpowelson** [comment]
@Levi-Armstrong Did something in the docker images change? I don't understand why this PR suddenly broke everything. Now it seems like it isn't using C++17. Is this because of Tesseract CMake changes?

**Comment by mpowelson** [comment]
@Levi-Armstrong Are you still ok with this change? I didn't merge them before because CI was failing

**Comment by Levi-Armstrong** [comment]
I am good with the change, but was the Focal build passing before?

**Comment by mpowelson** [comment]
I assumed not. I figured that was why it was not required. VAHCD is failing

**Comment by Levi-Armstrong** [comment]
It looks like focal added a new check. If `ignored-qualifiers` is added to the push/pop macro it should pass.

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
